Nop.Plugin.Payments.QualpayCheckout/Controllers/QualpayCheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Payments.QualpayCheckout.Models;
using Nop.Plugin.Payments.QualpayCheckout.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Payments.QualpayCheckout.Controllers
{
    public class QualpayCheckoutController : BaseAdminController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly QualpayCheckoutManager _qualpayCheckoutManager;

        #endregion

        #region Ctor

        public QualpayCheckoutController(ILocalizationService localizationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            QualpayCheckoutManager qualpayCheckoutManager)
        {
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._settingService = settingService;
            this._storeContext = storeContext;
            this._qualpayCheckoutManager = qualpayCheckoutManager;
        }

        #endregion

        #region Methods

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<QualpayCheckoutSettings>(storeScope);

            //prepare model
            var model = new ConfigurationModel
            {
                MerchantId = settings.MerchantId,
                MerchantEmail = settings.MerchantEmail,
                SecurityKey = settings.SecurityKey,
                EnableEmailReceipts = settings.EnableEmailReceipts,
                UseSandbox = settings.UseSandbox,
                AdditionalFee = settings.AdditionalFee,
                AdditionalFeePercentage = settings.AdditionalFeePercentage,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.SecurityKey_OverrideForStore = _settingService.SettingExists(settings, x => x.SecurityKey, storeScope);
                model.EnableEmailReceipts_OverrideForStore = _settingService.SettingExists(settings, x => x.EnableEmailReceipts, storeScope);
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(settings, x => x.UseSandbox, storeScope);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(settings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(settings, x => x.AdditionalFeePercentage, storeScope);
            }

            return View("~/Plugins/Payments.QualpayCheckout/Views/Configure.cshtml", model);
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<QualpayCheckoutSettings>(storeScope);

            //save settings
            settings.MerchantId = model.MerchantId;
            settings.SecurityKey = model.SecurityKey;
            settings.EnableEmailReceipts = model.EnableEmailReceipts;
            settings.UseSandbox = model.UseSandbox;
            settings.AdditionalFee = model.AdditionalFee;
            settings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSetting(settings, x => x.MerchantId, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.SecurityKey, model.SecurityKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.EnableEmailReceipts, model.EnableEmailReceipts_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("subscribe")]
        public IActionResult Subscribe(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings
            var settings = _settingService.LoadSetting<QualpayCheckoutSettings>();
            if (settings.MerchantEmail == model.MerchantEmail)
                return Configure();

            //try to subscribe/unsubscribe
            var successfullySubscribed = _qualpayCheckoutManager.SubscribeToQualpay(model.MerchantEmail);
            if (successfullySubscribed)
            {
                //save settings and display success notification
                settings.MerchantEmail = model.MerchantEmail;
                _settingService.SaveSetting(settings);

                var message = !string.IsNullOrEmpty(model.MerchantEmail)
                    ? _localizationService.GetResource("Plugins.Payments.QualpayCheckout.Subscribe.Success")
                    : _localizationService.GetResource("Plugins.Payments.QualpayCheckout.Unsubscribe.Success");
                SuccessNotification(message);
            }
            else
                ErrorNotification("Plugins.Payments.QualpayCheckout.Subscribe.Error");

            return Configure();
        }

        #endregion
    }
}

Nop.Plugin.Payments.QualpayCheckout/Views/Configure.cshtml
@model Nop.Plugin.Payments.QualpayCheckout.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="QualpayCheckout" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    Please enter your email to receive an information about special offers from Qualpay
                </p>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MerchantEmail" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantEmail" />
                        <span asp-validation-for="MerchantEmail"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="subscribe" class="btn btn-primary" value="@T("Plugins.Payments.QualpayCheckout.Subscribe")" />
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    For plugin configuration follow these steps:<br />
                    <br />
                    1. <a href="http://www.qualpay.com/nopcommerce" target="_blank">Create Qualpay account</a><br />
                    2. Log in at the <a href="https://app.qualpay.com/" target="_blank">production service</a>
                    or at the <a href="https://app-test.qualpay.com/" target="_blank"> sandbox service</a><br />
                    3. Go to the 'Administration' -> 'API Security Keys' and find Security Key<br />
                    4. Fill in your Qualpay Checkout credentials below<br />
                    5. Ensure you enable access to the Checkout API in your Qualpay account -> 'Administration' -> 'API Security Keys' -> Manage Access<br />
                    6. Save<br />
                    <br />
                    <em>Note: Qualpay Checkout supports only USD currency, so ensure that you have configured the USD as your primary store currency.</em><br />
                </p>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecurityKey_OverrideForStore" asp-input="SecurityKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecurityKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecurityKey" />
                        <span asp-validation-for="SecurityKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableEmailReceipts_OverrideForStore" asp-input="EnableEmailReceipts" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableEmailReceipts" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="EnableEmailReceipts" />
                        <span asp-validation-for="EnableEmailReceipts"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.QualpayCheckout/Views/PaymentInfo.cshtml
@{
    Layout = "";
}

<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.QualpayCheckout.RedirectionTip")</b></p>
        </td>
    </tr>
</table>